services:
  discovery:
    build: ./discovery
    container_name: discovery
    ports:
      - "8761:8761"
    expose:
      - "8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 5s
  config:
    build: ./config_server
    container_name: config
    ports:
      - "9999:9999"
    expose:
      - "9999"
    depends_on:
      discovery:
        condition: service_healthy
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery:8761/eureka
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 5s
  customer:
    build: ./customer
    container_name: customer
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      config:
        condition: service_healthy
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery:8761/eureka
      - CONFIG_SERVICE_URL=http://config:9999
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 5s
  account:
    build: ./account
    container_name: account
    ports:
      - "8081:8081"
    expose:
      - "8081"
    depends_on:
      customer:
        condition: service_healthy
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery:8761/eureka
      - CONFIG_SERVICE_URL=http://config:9999
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 5s
  account2:
    build: ./account
    container_name: account2
    ports:
      - "8083:8083"
    expose:
      - "8083"
    depends_on:
      customer:
        condition: service_healthy
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery:8761/eureka
      - CONFIG_SERVICE_URL=http://config:9999
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/actuator/health" ]
      interval: 5s
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8888:8888"
    expose:
      - "8888"
    depends_on:
      account:
        condition: service_healthy
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery:8761/eureka
      - CONFIG_SERVICE_URL=http://config:9999